main.go
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
=> prevent externals from trigger jenkins

main.go
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
=> build rpi3 images when targeting meta-mender/poky

main.go
=> Remove Github status update parameters, since they are automatic now.

main.go
Signed-off-by: Gregorio Di Stefano <greg.distefano+github@gmail.com>
=> only build BBB

main.go
=> Add functionality for disabling integration tests in a PR body

main.go
=> include useradm-enerprise in watch repos

main.go
Porting commit a390fcd to GitLab branch
=> GitLab runner: Include useradm-enerprise in watch repos

main.go
=> QA-107: Do not trigger builds for Draft PR's on Github

helpers.go, main.go
=> Added Inventory-Enterprise synchronization functionality to the test-runner

main.go
This simply adds workflows-enterprise as a repository to be kept in sync
automatically by the integration-test-runner.
=> Added workflows-enterprise code synchronization

main.go
Amend of #29 
Already deployed to production and now it works :ok_hand:
=> Prepend baseBranch with 'origin/' to use in --version-of

main.go
This adds a point by point recipe for how to fix OS -> Enterprise merge
conflicts locally, and then push them to the PR branch, once they are resolved.
=> Added a comment on how tolocally resolve OS -> Ent merge conflicts

main.go
This adds a simple markdown table with the build variables used for this
particular build.
Handy to make sure that the build is from a cross-repo build or not.
=> Added the build matrix to the build started comment

main.go
=> Forgot to run the ID and WebURL pipelines

main.go
=> fix newline in build matrix template

.gitlab-ci.yml, Dockerfile, docker-compose.yaml, helpers.go, kubernetes.yaml, main.go
Added the required files to build and run the tool through a Linux
container.
The docker-compose.yaml file is added aiming for local development while
the kubernetes.yaml file will describe the future deployment in the
production VM.
Added a pipeline to perform Go static checks and carry the build/publish
of the image.
=> QA-192: Containerize tool and introduce Pipeline to the repo

main.go
This repository is now private.
=> Add mender-api-docs to the list of repos to sync

helpers.go
=> Extend the validDependabotPR check to accept re-opened PR's

helpers.go, main.go
Depends on https://github.com/mendersoftware/integration/pull/1066
=> QA-226: Use new release_tool CLI option to run feature branches pipeline

main.go
And trigger full yocto builds on PRs to this repo.
=> MEN-4084: Add mender-shell to the watch of the bot

main.go
Changelog: none
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>
=> MEN-4292: rename mender-shell to mender-connect

log.go, main.go
Using logrus Hook interface. Commit fdefa68 was insufficient.
=> Correctly implement the delivery field in the logs

main.go, pullreq_pipeline.go
=> QA-264: Delete pr_x branch in Gitlab upon a close or merge

menderqa_pipeline.go, menderqa_pipeline_helpers.go
Changelog: none
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>
=> Set the right working directory in getListOfVersionedRepositories

cherrypicks.go, cherrypicks_test.go
Changelog: none
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>
=> QA-232: handle cherry-pick suggestions with less than three branches

cherrypicks.go, entfork_sync.go, git/git.go, gitlab_sync.go, go.mod, go.sum
A lot of our code has 100+ lines of basically git boiler plate.
This adds a utility package, for executing batch git commands.
Just want to see if I should finish this, I think it'd be a nice addition?
=> Add a utility function for batching git commands

gitlab_sync.go
We were pushing to the same place we were pulling from...
=> [gitlab_sync] Correct GitLab remote URL

entfork_sync.go
=> Remove the extraneous git command to git.Command

main.go
And remove mender-python-client-dev
=> Add monitor-client to watch repos list

main_pullrequest.go, pullreq_pipeline.go, tests/tests/test_github_webhooks.py
Reverts mendersoftware/integration-test-runner#100
=> Revert "Pull Request sync add gitlab CI_EXTERNAL_* environment"

main.go
Removed by mistake in b091b6a.
=> Add meta-mender to the list of repos to watch

tests/tests/test_github_webhooks.py
Namely devicemonitor and monitor-client
=> Fix acceptance tests after new repositories

main.go
=> MEN-5149 Azure IoT Manager repository added.

Makefile, tests/run.sh, tests/tests/golden-files/test_cherrypick.yml, tests/tests/golden-files/test_issue_comment.yml, tests/tests/golden-files/test_issue_comment___pr.yml, tests/tests/golden-files/test_issue_comment_minor_series.yml, tests/tests/golden-files/test_pull_request_closed.yml, tests/tests/golden-files/test_pull_request_opened_from_branch.yml, tests/tests/golden-files/test_pull_request_opened_from_fork.yml, tests/tests/golden-files/test_push_cfengine.yml, tests/tests/golden-files/test_push_mender_qa_repo.yml, tests/tests/golden-files/test_push_mendersoftware.yml, tests/tests/test_github_webhooks.py
=> Move the acceptance tests to follow a golden file test style

main_comment.go, tests/tests/payloads/issue_comment___pr.json
=> start pipeline --pr repo/N; where N is the pull request number support.

tests/tests/golden-files/test_issue_comment___pr.yml, tests/tests/golden-files/test_pull_request_closed.yml
=> Tests alignment after removal of mender-auth-azure-iot from component

main_pullrequest.go, main_pullrequest_test.go, tests/tests/golden-files/test_pull_request_opened_from_branch.yml, tests/tests/golden-files/test_pull_request_opened_from_fork.yml, tests/tests/payloads/pull_request_opened_from_fork.json
=> QA-336 Create the pr_ branches with exceptions

main_pullrequest.go
=> QA-353 Basic commands and options summary.

main_pullrequest.go
=> Comment on new pull request fix: add a new msg, not replace.

main_pullrequest.go, tests/tests/golden-files/test_pull_request_opened_from_branch.yml
=> QA-336 Run gitlab pipelines for pr_ branch only

gitlab_sync.go, gitlab_sync_test.go
=> QA-336 Switch ci.skip for all branches synced from github.

main_pullrequest.go, tests/tests/golden-files/test_issue_comment___pr.yml, tests/tests/golden-files/test_pull_request_closed.yml, tests/tests/test_github_webhooks.py
=> typo: instructional comment mentions wrong syntax

.gitlab-ci.yml, cherrypicks.go, client/github/client.go, client/gitlab/client.go, entfork_sync.go, git/git.go, gitlab_sync.go, main.go, main_comment.go, main_pullrequest.go, main_push.go, menderqa_pipeline.go, menderqa_pipeline_helpers.go, pullreq_pipeline.go, util.go
And fix linting issues (mainly lines length).
=> Add lint check

gitlab_sync.go
To be able to update Mender Docs on merges to mender-docs/hosted.
=> Add hosted to the list of special branches for whom to run pipeline

cherrypicks_test.go, main_comment.go, main_comment_test.go, util.go
Adds new repo/pull/<pr_number> syntax to integration-test-runner
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
=> Adds new repo/pull/<pr_number> syntax to integration-test-runner

conventional_commits.go, tests/tests/golden-files/test_issue_comment_conventional_commit.yml
Signed-off-by: Mikael Torp-Holte <mikael.torp-holte@northern.tech>
=> Fix bug where test-bot could not retrieve dependabot commit message

cherrypicks_test.go
=> test: Update the cherry-pick tests to align with the 3.3.0 versions

cherrypicks.go, cherrypicks_test.go
Ticket: QA-381
Signed-off-by: Mikael Torp-Holte <mikael.torp-holte@northern.tech>
=> feat: cherry-pick suggestions based on version info in mender-docs

main.go, main_pullrequest.go
chore: update PR with mindful message on failures
Ticket: QA-346
fix: test-runner crashing
Ticket: MEN-5881
=> Test-runner crush fix and added PR comment updates on failures

main_pullrequest.go
Ticket: None
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>
Related Slack discussion - https://northern-tech.slack.com/archives/C0LCTK2CE/p1663856391659719
=> fix: don't post messages when the bot is used only to sync repos

cherrypicks.go, cherrypicks_test.go
https://tracker.mender.io/browse/QA-471
=> chore: cherry-pick unit test to test against static json

tests/tests/golden-files/test_pull_request_closed.yml
=> ci: Reflect the added mender-ci-workflows service in the tests

main_pullrequest.go
=> fix: Don't post a new changelog when text hasn't changed.

tests/tests/golden-files/test_feature-c++-client_branch.yml
=> test: Fix tests after integration/feature-c++-client branch was updated.

main_pullrequest.go
This should help mitigate some of the issues we are seeing starting pipes, when
the base branch is not (yet) present.
Ticket: QA-519
=> fix: retry the pipeline start in case of errors

main.go, main_comment.go, main_pullrequest.go
=> QA-566: feat: sync command to trigger repos sync by a comment

main.go
=> feat: added NorthernTechHQ sync

.gitlab-ci.yml
=> feat: added deployment to northerntechhq org

README.md
=> chore: updated doc for the github gitlab sync

cherrypicks.go
=> fix: cherry-pick suggestions when no master is present 

.gitlab-ci.yml
=> chore: fix pipeline acceptance tests

tests/tests/golden-files/test_feature-c++-client_branch.yml
After `integration` update in:
* https://github.com/mendersoftware/integration/pull/2454
=> test: Update golden file for feature branch test

tests/tests/golden-files/test_issue_comment.yml, tests/tests/golden-files/test_issue_comment___pr.yml, tests/tests/golden-files/test_pull_request_closed.yml
After:
* https://github.com/mendersoftware/integration/pull/2486
=> test: Remove reporting variable from golden files

tests/tests/golden-files/test_feature-c++-client_branch.yml
Follow-up from:
* https://github.com/mendersoftware/integration/pull/2497
=> chore: Update golden files after `feature-c++-client` branch update

cherrypicks.go, cherrypicks_test.go
=> fix(smiley-cat): Fix all smiley cat emojis

menderqa_pipeline.go
The `mender-qa` repository introduced a breaking change for Mender 3.7 and earlier, so we need to launch these builds with the legacy branch.
See:
* https://github.com/mendersoftware/mender-qa/pull/750
=> chore: Fix integration pipeline for legacy builds

main_comment.go, pullreq_pipeline.go
=> fix: don't return error on 404 when deleting protected branches
