main.go

This is needed because gui has a Mender version, but is not watched by
the test runner.

Maintain a separate list of repositories with Mender versions.

---

main.go

Fix: The PR-Body is contained in the PullRequest struct

---

main.go

https://tracker.mender.io/browse/MEN-2652
supports https://github.com/mendersoftware/deployments-enterprise/pull/1
@kacf is this the correct way to automatically start integration for a repo?

include deployments-enterprise in watch repos

---

main.go

Stop treating tenantadm specially and treat as release repo.

---

main.go

Note: This functionality relies on an external tool:
https://github.com/containous/gallienii to keep the repos in sync. When the
integration-test-runner detects a merge into one of the OS repositories with an
Enterprise fork, then an HTTP GET request is sent to the gallienii server, which
is running as a seperate service on the server. Then gallienii will run its sync
functionality which syncs all Enterprise repos with its OS counterpart. Note
that this is not specific to the merged PR, and hence all unsynchronized code
across all Enterprise repos will get a PR with the missing code. The gallienii
server will be listening to a configureable port, given by the GALLIENI_PORT
environment variable.

QA-107: Keep OS and Enterprise repos in sync

---

main.go

The Github PR's will not get the status 'opened', like a regular PR when moved
out of the 'Draft' state. However, it gets the status 'ready_for_review', which
currently is not a recognized action in the integration-test-runner.
This fix adds the 'ready_for_review' status to the accepted status for builds.

Fix: Build PR's moved out of the 'Draft' status

---

main.go

No need to keep running a PR test-pipeline if the tests have already been
merged. Thus kill the stale-builds, and return.

QA-122: Stop stale builds when merging a PR

---

helpers.go
main.go

The previous approach will not work when adding new repos: these will be
listed in master but not present in integration/2.x.x branches.
The original reason to do this clones is unknown.

QA-171: Redo function to use --in-integration-version

---

main.go

Up until now, all our repos have been ported to "Mender" subgroup, but
from now on we will have some repos in different groups (aka SaaS).
Let the code define which repos go to a different subgroup.

Support for different GitLab sumgroups

---

main.go

There is really no need for the empty placeholders I think.
Besides, it's fugly.

Only show non-empty values in the build matrix

---

Dockerfile
docker-compose.yaml
entrypoint
main.go

* Listen for the hook in root instead of incoming
As the tool will have a dedicated domain when deployed in the new infra.
* Add missing dependencies and initialization to the image
The image was missing:
* openssh
* SSH client initialization
* release tool dependencies (pyyaml)
* release tool in path
* Commented out in docker-compose file how the SSH keys are expected to be
mounted in the container.

Fixes for image in kubernetes

---

.gitlab-ci.yml

It seems like these functions don't get exposed out of the templates as
expected.

[pipeline] Redefine locally .export_docker_vars

---

.gitlab-ci.yml

So that we make sure that the image has been successfully published into
the registry before attempting to update the cluster.

[pipeline] Move deploy job to new stage trigger

---

helpers.go
main.go

Since Github's Dependabot does not support vendoring in Go, a manual step has to
be applied after a PR is opened with a dependency upgrade.
This commit will add the functionality, by having the bot fetch the remote
branch, vendor and tidy the repository, and push the new commit.

QA-201: Vendor dependabot PR's

---

Dockerfile

So as to have the go binary present in the image.

Change the running container to golang:1.14-alpine3.11

---

main.go

From now on, we use meta-openembedded in the tests, so it is important
to set it to the right branch. Once we are on it, set meta-raspberrypi
too to be future ready.

Select the correct poky branch on related yocto repos

---

main.go

By skipping any builds.
Also:
* Clean references to our old CI server
* Remove BASE_BRANCH parameter, which is unused in the pipeline
* Fix typos in comment

Handle meta-mender PRs targeting "master-next"

---

main.go

This repo is not really used in integration pipeline (is only built and
potentially published). So the value of running it on mender-cli PRs is
very limited.

Remove mender-cli from the watch repositories list

---

main.go

If I'm not mistaken, there is a slight logic error here: https://github.com/mendersoftware/integration-test-runner/pull/54/commits/f4b4cc504e53eba967e94a26c9ab5f375ccd2358
Second commit is optional. I just liked the sound better :)

Re-enable meta-mender builds on PR's

---

helpers.go

Previously printed error messages from release-tool.py were simply ignored upon
an error, even though these can be mighty helpful when debugging an issue.
This wraps all errors in helpers.go with the std-output returned from the release-tool.

Add release-tool.py error output to the error messages

---

main.go

Parameter `repoOS` was not being set, so the resulting comment was always
something like `mender-test-bot/-enterprise.git`.
Fix by just remove this parameter and using `repo` instead.

Fix typo in conflict's comment

---

Dockerfile
README.md
entrypoint
main.go

* Configurable list of repos for which to do GitHub->GitLab sync
Rework a bit the config to allow for a configurable list of repositories
to sync via env variable WATCH_REPOS_SYNC.
* Make Git config user/email configurable via env variables
These are only required for operations that perform "git commit", like
dependabot's commits amend.
* Add some minimal documentation on the three main features
* Extend the sync and PR branches features to CFEngine
Namely, map GitHub organizations to GitLab groups, so that we can use
these features on both organizations.

Sync repos configurable

---

main.go

The previous filed seems to not exist in pull_request events.

Take the organization name from the top level Organization

---

main.go

Use os.LookupEnv to check for empty env variables, so that a user can
set WATCH_REPOS_PIPELINE or WATCH_REPOS_SYNC to "" to indicate no
repository in the list.

Allow for user setting empty watch lists

---

.gitlab-ci.yml

Changelog: none
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

QA-257: update CD pipeline to use the sync:image job from templates

---

menderqa_pipeline.go

This takes advantage of the functionality in:
https://github.com/mendersoftware/mender-qa/pull/481
And sets BUILD_CLIENT == false, in the case a repository in the
prebuiltClientRepositories array is targeted.

QA-255: Do not build the mender-client from source unneeded

---

pullreq_pipeline.go
util.go

We want to access the org of the PR, not the org of the repo...
Quoted also the getRemoteURLGitLab output to easily identify a blank org
variable.

deleteStaleGitlabPRBranch: fix "Failed to delete the stale PR branch"

---

cherrypicks.go
cherrypicks_test.go

And fix existing tests.
This fix will catch the next iteration of a changelog like the one at https://github.com/mendersoftware/mender-connect/pull/29

[cherrypicks] Accept Changelog entries with no space after colon

---

client/github/client.go
client/github/mocks/Client.go
main_pullrequest.go
main_pullrequest_test.go

The bot can be kinda noisy if there are a lot of pushes to a PR.
This makes sure that if there is a comment from the bot already, there is no new
comment posted.

Only comment once on a PR

---

main_pullrequest.go

The retrieval of the repo owner does not work, also, everywhere else in code
defaults to githubOrganization, which is hardcoded to 'mendersoftware'.
This should fix the error the bot is currently having, see the logs:
```
2021-04-27 16:48:14.000 CEST
Failed to list the comments on PR: mender/741, err: 'GET https://api.github.com/repos//mender/issues/741/comments?direction=asc&sort=created: 404 Not Found []'
```
And note the missing 'mendersoftware' specification.

Fix: Use the hardcoded github organization as the repo owner

---

main_pullrequest.go
pullreq_pipeline.go

The functionality is meant to do branches from our forks, but some times
we do have PRs coming from actual branches, ending up with duplicate
pipelines running...

[pullreq_pipeline] Do not create branches for PRs coming from branches

---

main.go
main_push.go

[QA-318] Default to syncing ALL repositories when processing push webhooks

---

main_pullrequest.go
pullreq_pipeline.go
tests/tests/test_github_webhooks.py

This pull request will sync ALL pull requests to gitlab by setting ci
variables as push options. However, if the pr is comming from the
upstream repository, the corresponding gitlab branch is force-pushed.
FYI @tranchitella @lluiscampos this PR addresses the coverage reports not referring to the PR base.

Pull Request sync add gitlab CI_EXTERNAL_* environment

---

main.go
main_pullrequest.go
menderqa_pipeline.go
pullreq_pipeline.go
tests/tests/test_github_webhooks.py

This PR will explicitly start a new pipeline when is created or changes state (except for closing/merging), with the `CI_EXTERNAL_*` environment defined [here](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#predefined-variables-for-external-pull-request-pipelines).

PRs: Mimick gitlab repository mirroring environment vars

---

gitlab_sync.go
main.go
tests/tests/payloads/push_mender_qa_repo.json
tests/tests/test_github_webhooks.py

The build after sync for this repo (namely: on master) are virtually
always a waste of resources; any other repo (or in the worst case, in
the night) will be using mender-qa/master in the next integration
pipeline build.
And for the very few cases were it can be useful, is better to trigger
it manually.

gitlab_sync: Do not trigger CI build for mender-qa syncs

---

cherrypicks_test.go
menderqa_pipeline_helpers.go
tests/tests/test_github_webhooks.py

Though it's probably not the safest way to strip the "ref directory", the same logic is used elsewhere...

FIX: Remotes appearing in branchnames

---

.gitlab-ci.yml
README.md

Which uses the same image as mender-test-runner.
Bonus:
* README: Update GitHub->GitLab sync information
It is not configurable since 1b4bc61.

Enable CD for cfengine-repos-sync deployment too

---

cherrypicks.go
cherrypicks_test.go
entfork_sync.go
gitlab_sync.go
main.go
main_comment.go
main_comment_test.go
main_pullrequest.go
main_pullrequest_test.go
menderqa_pipeline.go
pullreq_pipeline.go
util.go

Instead of hard-coding it to `mendersoftware`, so that it can be used by
other GitHub Organizations (namely: CFEngine).

Extract GitHub Organization from webhooks payload

---

cherrypicks.go

The extra 2.7.2 release messes with the latest release heuristic used for
picking out the latest releases.
JIRA ticket https://tracker.mender.io/browse/MEN-5212 is created for tracking this.

handle the 2.7.x release exception

---

main.go
menderqa_pipeline.go
menderqa_pipeline_helpers.go
tests/tests/golden-files/test_pull_request_opened_from_branch.yml

So that we remove one point of duplication in our ecosystem.
The list was only being used to trigger in which repos to offer the
"start pipeline" functionality. Instead of a full list, hard-code only
the repos that are not part of the tool (namely: meta-mender).
The only drawback is that we are now suggesting in `gui` to start the
pipeline, but this might come in handy in the future if we integrate the
e2e tests with mender-qa.

menderqa_pipeline: Base the watch repositories list in release_tool list

---

cherrypicks.go
cherrypicks_test.go
tests/tests/golden-files/test_issue_comment___pr.yml
tests/tests/golden-files/test_pull_request_closed.yml

Previously cherry-picks were only supported in release branches matching some
release version, like `1.2.x`.
Now, this functionality is extended to the standard branchnames, like:
* master
* hosted
* staging
* production

fix: cherry-picks to standard branches now supported

---

main_pullrequest.go

Ticket: INF-3042
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>

fix: false positive errors PR comments in CFEngine repos

---

Dockerfile
Dockerfile.acceptance

For some reason dependabot concludes that "Latest version is 1.14-alpine3.11" when parsing the `Dockerfile`, which I suspect is due to the bugfix version not being present.

chore: Use complete version for the Docker base images

---

integration_helpers.go
integration_helpers_test.go

fix: Prevent warnings from causing changelog reposting.

---

menderqa_pipeline.go
tests/tests/golden-files/test_feature-c++-client_branch.yml

Just pass some condition to mender-qa, so that we can conditionally build the cpp client recipe in Yocto.

chore: Add the BUILD_CPP_CLIENT environment variable

---

README.md
main.go
main_comment_test.go
main_push.go
tests/tests/golden-files/test_push_cfengine.yml
tests/tests/golden-files/test_push_mender_qa_repo.yml
tests/tests/golden-files/test_push_mendersoftware.yml

Ticket: [QA-518](https://tracker.mender.io/browse/QA-518)
With the change the following is achieved:
* it's possible to disable different features if some is not needed
* it's possible to set a list of managed repos and ignore the rest
The change is backward compatible and won't brake current deployments, but will allow to customise a deployment for CFEngine GitHub organisation.
Straight goal is to use the integration-test-runner to only sync specified list of repos for CFEngine GitHub organisation. With the implementation it can be achieved with using the following setup: `SYNC_REPOS_LIST="website,build"`, `NOT_PROCESS_PR_EVENTS="true"` and `NOT_PROCESS_COMMENTS="true"`

QA-518: add list of repos to sync option

---

main.go

The intention of the change is to improve logging to reduce amount of log entries, which will contribute to infra costs savings and making work with logs more comfortable.
The idea is to use `/_health` endpoint for the healthchecks by a load balancer and don't log those calls.

chore: Logging improvement

---

cherrypicks.go
cherrypicks_test.go

We don't always know if the latest version will need support in the future or
not, so we really have to cherry-pick to it, just in case.
Ticket: QA-496

feat: Also comment on cherry-picking to the latest released version

---

main_pullrequest.go

Dependabot sometimes does a lot of edits in a short timespan. This causes our
test-bot to try and sync the branch on every request, basically doing a simple
DDos of our branch syncing to GitLab.
The fix is simple. Just ignore edits to PR's, which really is the right thing to
do anyways.
Ticket: QA-538

fix: Do not process edited pull requests

---

cherrypicks.go
cherrypicks_test.go
gitlab_sync.go

Alvaldi will use `main` as default branch but I found issues with the GH > GL sync, for example pipeline skipped after merging PRs to `main`.
I hope this PR would fix the issues.

feat: added support for main branch

---

main_pullrequest.go

Otherwise GH takes the next line after `<br />` as raw text.

chore: Add missing newline in comment for proper markdown rendering

---

cherrypicks.go
tests/tests/golden-files/test_cherrypick_multiline.yml
tests/tests/golden-files/test_cherrypick_singleline.yml

Make the bot behave when cherry-picking empty commits, for example when amending changelog entries.

fix: Allow cherry-pick of empty commits

---

main.go
menderqa_pipeline.go
menderqa_pipeline_helpers.go

Originally this repository was not part of the release tool so it was appended as an extra repo to the watch list. However it was added to the tool at some point and now we were having two identical pipelines on PRs for this repository.

fix: Remove duplicated pipeline for `meta-mender` PRs

---

.gitlab-ci.yml

Fixes runc errors in the hetzner runner
Ticket: QA-823

ci: pin docker to v27.3

---

Dockerfile
Dockerfile.acceptance

We need a newer golang version in the unit tests, because go now allows patch-versions for the go version in the go.mod - which some newer dependencies require.
We also need this https://github.com/mendersoftware/mendertesting/pull/358

chore: bump golang-image versions

---

entfork_sync.go

The sync is managed through Gitlab CI

chore: Remove mender-server from entfork_sync

---

main_comment.go
pullreq_pipeline.go
tests/tests/golden-files/test_issue_comment_integration.yml
tests/tests/golden-files/test_pull_request_closed.yml

The fix should be best illustrated in the output from the golden files:
Before:  `gitlab.DeleteBranch: path=git@gitlab.com:Northern.tech/Mender/integration,branch=pr_2725_protected`
Now: `gitlab.DeleteBranch: path=Northern.tech/Mender/integration,branch=pr_2725_protected`
I am pretty sure that this is why it returned 404 even though the branch existed.

Fix delete

---

client/gitlab/client.go
pullreq_pipeline.go
tests/tests/golden-files/test_issue_comment_integration.yml
tests/tests/golden-files/test_pull_request_closed.yml

Just deleting the branch will still leave the protection rule in Gitlab. When attempting to sync a branch while the protection is there, we will get 409 conflict errors. Therefore we want to unprotect the branch after deleting it to ensure we can re-create it and that the protection rule is deleted after closing / merging a PR.
Ticket: None

fix: attempt to unprotect branches after deleting them

---

main_comment.go

See the latest runs here: https://github.com/mendersoftware/integration/pull/2730
It works sometimes, and (seemingly) always after closing and re-opening the pr. This leads me to believe the syncing sometimes happens before the deletion has completed, giving errors like:
```There was an error while syncing branches: [push -f -o ci.skip --set-upstream gitlab pr_2730_protected] returned error: remote: GitLab: You are not allowed to create protected branches on this project.
To gitlab.com:Northern.tech/Mender/integration
! [remote rejected] pr_2730_protected -> pr_2730_protected (pre-receive hook declined)
error: failed to push some refs to 'gitlab.com:Northern.tech/Mender/integration'
: exit status 1 returned error: There was an error syncing branches: [push -f -o ci.skip --set-upstream …
```

fix: wait between deletion and syncing branches

---

main.go
main_pullrequest.go
main_pullrequest_test.go
tests/tests/golden-files/test_pull_request_opened_from_fork.yml

If a PR title starts with `[NoCI]` (case insensitive) the CI will not be started automatically.

QA-972: Add option to skip CI from PR title

---

main_pullrequest.go

Client pipelines now print:
`mentioning me and `start client pipeline"start client pipeline".`
This seems to be caused by a mixed use of backticks and double quotes: "`" + commandStartClientPipeline + `"`.
Updated the integration pipeline comment to use the `commandStartIntegrationPipeline` variable instead of hardcoding the string
Ticket: None

fix: correct formatting of bot comment string

---

main_pullrequest.go

`commandStartClientPipeline` is already a part of `botCommentString`. resulting in `mentioning me and 'start client pipeline'start client pipeline".`
https://github.com/mendersoftware/integration-test-runner/pull/379 didn't actually address the issue.

fix: remove extra `commandStartClientPipeline` from bot message
